baseURL = "http://rewong03.github.io"
title = "Ryan E. Wong"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

publishDir = "rewong03.github.io"

[params]
    author = "Ryan Wong"
    description = "Ryan Wong's personal website"
    info = "Student @ Whitney Young HS"
    #avatarURL = "images/avatar.jpg"

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/rewong03/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/rewong03/"
